DELIMITER  //

CREATE PROCEDURE accountDelete(accountIdIn INT)
BEGIN

SET FOREIGN_KEY_CHECKS=0;
DELETE FROM Accounts WHERE account_accountId = accountIdIn;
SET FOREIGN_KEY_CHECKS=1;

END;
//

DELIMITER ;